#Typewriter effect function
import sys
import time
import random

# I wanted the game to have a typewriter effect so I included this one, which I asked AI about. All in all, lines 7-12 are the only ones generated by AI
def typewriter_effect(text, delay=0.01):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    print() 

#Enter your name and name the guide
name = str(input('Enter your name: '))
#Introduction and instructions
typewriter_effect(f"Welcome {name} to the Adventure Game! I will be your Guide for this adventure. What do you wish to call me?")
bname = input('Guide Name: ')
typewriter_effect(f'{bname}: Great! Before we begin, do you want to read the instructions? (yes/no)')
user_int = input(f'{name}: ')
while user_int.lower() not in ['yes', 'no']:
   user_int = input('Please enter yes or no: ')
if user_int.lower() == 'yes':
    typewriter_effect("Instructions: In this game, you will embark on a thrilling adventure. Make choices by typing the options provided. You will choose your class, which determines the type of abilities and attributes that you will have, and also the type of weapons that you can buy and use. You will enter and explore dungeons filled with so many undetermined possibilities, so hold tight on your luck! Your decisions will shape your journey. Understood?")
    input(f'{name}: Okay! (enter) ')
elif user_int.lower() == 'no':
    typewriter_effect('Alright, let\'s get started!')

#User status before choosing class - everything at 0 until a class is picked
health = 0
mana = 0
strength = 0
defense = 0
intelligence = 0
agility = 0
money = 0
inventory = 0
classs = ""
weapon = ""
spell = ""
#Choosing your class
typewriter_effect('Great! Now, let\'s choose your class. You can be a Warrior, Mage, Archer, or Tank. Each class has its own strengths and weaknesses. Do you want to know more about each class or do you want to proceed and choose your class? (more/proceed)')
class_info = input(f'{name}: ')
while class_info.lower() not in ['more', 'proceed']:
   class_info = input('Please enter more or proceed: ')
if class_info.lower() == 'more':
    typewriter_effect('Warrior: High strength and defense, excels in close combat. \nMage: High intelligence and magic power, excels in casting spells. (recommended option) \nArcher: High agility and precision, excels in ranged attacks. \nTank: Extremely high defense and health, excels in absorbing damage. (recommended option)')
    typewriter_effect('Now that you know more about the classes, which class do you want to choose? (Warrior/Mage/Archer/Tank)')
elif class_info.lower() == 'proceed':  #was missing .lower() so 'Proceed' would slip through
    typewriter_effect('Alright, which class do you want to choose? (Warrior/Mage/Archer/Tank)')
chosen_class = input(f'{name}: ')
while chosen_class.lower() not in ['warrior', 'mage', 'archer', 'tank']:
   chosen_class = input('Please choose a valid class: ')
if chosen_class.lower() == 'warrior':
    typewriter_effect('You have chosen the Warrior class. Warriors are known for their strength and defense, making them formidable in close combat. You have the following stats: \nStrength: 8 \nDefense: 7 \nIntelligence: 3 \nAgility: 5 \nHealth: 100 \nMana: 30')
    health = 100
    mana = 30
    strength = 8
    defense = 7
    intelligence = 3
    agility = 5
    classs = 'Warrior'
elif chosen_class.lower() == 'mage':  #changed to .lower() so any combination of uppercase works
    typewriter_effect('You have chosen the Mage class. Mages are known for their intelligence and magic power, making them formidable spellcasters. You have the following stats: \nStrength: 3 \nDefense: 4 \nIntelligence: 9 \nAgility: 5 \nHealth: 70 \nMana: 100')
    health = 70
    mana = 100
    strength = 3
    defense = 4
    intelligence = 9
    agility = 5
    classs = 'Mage'
elif chosen_class.lower() == 'archer':  #same fix as mage
    typewriter_effect('You have chosen the Archer class. Archers are known for their agility and precision, making them formidable ranged attackers. You have the following stats: \nStrength: 5 \nDefense: 4 \nIntelligence: 5 \nAgility: 8 \nHealth: 80 \nMana: 50')
    health = 80
    mana = 50
    strength = 5
    defense = 4
    intelligence = 5
    agility = 8
    classs = 'Archer'
elif chosen_class.lower() == 'tank':  #same fix as mage
    typewriter_effect('You have chosen the Tank class. Tanks are known for their extremely high defense and health, making them formidable damage absorbers for the team. You have the following stats: \nStrength: 6 \nDefense: 10 \nIntelligence: 3 \nAgility: 2 \nHealth: 135 \nMana: 20')
    health = 135
    mana = 20
    strength = 6
    defense = 10
    intelligence = 3
    agility = 2
    classs = 'Tank'
#Begin explore - class is confirmed, now we set things in motion
typewriter_effect('Now let\'s head to the shop to get you equipped for your adventure!')
input(f"{name}: ")

#player has no money yet so we have to get some before the shop - first decision of the game
bankt = "Bank Teller"
win = 0
typewriter_effect('Ohhhh no! It seems that you don\'t have any money to buy equipment! You need to get some money first before you can buy anything. Let\'s head to somewhere to get some money!')
input(f'{name}: Okay...')
typewriter_effect(f"{bname}: Oh look! There\'s a bank there... and there\'s a psychic outside the bank... Maybe the psychic can help you get some money... or we can loan something from the bank... Where do you wanna go? Though I personally suggest going to the bank first... (psychic/bank)")
place = input(f'{name}: ')
while place != 'psychic' and place != 'bank' and place != 'Psychic' and place != 'Bank' and place != 'PSYCHIC' and place != 'BANK' and place != 'pSychic' and place != 'bAnk' and place != 'PsYchic' and place != 'BaNk' and place != 'PSYchic' and place != 'BANk' and place != 'PSYChic' and place != 'BANk':
    place = input('Please enter psychic or bank: ')
if place == 'bank' or place == 'Bank' or place == 'BANK' or place == 'bAnk' or place == 'BaNk' or place == 'BANk':
    typewriter_effect('You went to the bank', delay=0.05)
    input()
    typewriter_effect(f'{bankt}: Hello, how can I help you today?')
    input()
    typewriter_effect(f'{name}: Hi, I need to get some money to buy equipment for my adventure. Can I take a loan?')
    input()
    typewriter_effect(f'{bankt}: Yes, you absolutely can! But you need an account with us first. Do you have an account with us? (yes/no)')
    acc = input(f'{name}: ')
    while acc != 'yes' and acc != 'no' and acc != 'Yes' and acc != 'No' and acc != 'YES' and acc != 'NO' and acc != 'yEs' and acc != 'nO' and acc != 'YeS' and acc != 'No' and acc != 'yES' and acc != 'nO' and acc != 'YEs' and acc != 'nO':
         acc = input('Please enter yes or no: ')
    if acc == 'yes':
        typewriter_effect(f'{bankt}: Great! Can I have your account number please?')
        acc_num = input(f'{name}: ')
        typewriter_effect(f'{bankt}: Thank you! Let me check your account.')
        typewriter_effect("Checking...", delay=0.18)
        typewriter_effect(f'{bankt}: Oh. Unfortunately, it seems that the account number you provided is invalid or does not exist. Do you want to try again? (yes/no)')
        try_again = input(f'{name}: ')
        while try_again != 'yes' and try_again != 'no' and try_again != 'Yes' and try_again != 'No' and try_again != 'YES' and try_again != 'NO' and try_again != 'yEs' and try_again != 'nO' and try_again != 'YeS' and try_again != 'No' and try_again != 'yES' and try_again != 'nO' and try_again != 'YEs' and try_again != 'nO':
                try_again = input('Please enter yes or no: ')
        if try_again == 'yes':
            typewriter_effect(f'{bankt}: Alright, please provide your account number again.')
            acc_num = input(f'{name}: ')
            typewriter_effect(f'{bankt}: Thank you! Let me check your account...')
            typewriter_effect("Checking...", delay=0.18)
            typewriter_effect(f'{bankt}: Oh. Unfortunately, it seems that the account number you provided is invalid or does not exist. I\'m sorry but you can\'t take a loan without a valid account.')
            input(f'{name}: Oh okay...')
            input()
            typewriter_effect(f'{bankt}: Alright, have a nice day!')
            input()
            typewriter_effect(f"{bankt}: ...")
            input()
            typewriter_effect(f'{bankt}: Oh WAITT!!! I almost forgot!!.')
            input()
            typewriter_effect(f'{name}: Huh? WHat is it?')
            input()
            typewriter_effect(f'{bankt}: We actually have an event right now where you try to guess the password of a dummy bank account, and if you guess it right, you get $50! Do you want to try? (yes/no)')
            try_event = input(f'{name}: ')
            while try_event != 'yes' and try_event != 'no' and try_event != 'Yes' and try_event != 'No' and try_event != 'YES' and try_event != 'NO' and try_event != 'yEs' and try_event != 'nO' and try_event != 'YeS' and try_event != 'No' and try_event != 'yES' and try_event != 'nO' and try_event != 'YEs' and try_event != 'nO':
                try_event = input('Please enter yes or no: ')
            if try_event == 'yes':
                typewriter_effect(f'{bankt}: Great! The password has 1 digit. However, it\'s randomized, so after each attempt a new password is created. You have twenty tries to guess it right. Wanna try now? (yes/no)')
                try_now = input(f'{name}: ')
                while try_now != 'yes' and try_now != 'no' and try_now != 'Yes' and try_now != 'No' and try_now != 'YES' and try_now != 'NO' and try_now != 'yEs' and try_now != 'nO' and try_now != 'YeS' and try_now != 'No' and try_now != 'yES' and try_now != 'nO' and try_now != 'YEs' and try_now != 'nO':
                    try_now = input('Please enter yes or no: ')
                if try_now == 'yes':
                    import random
                    tries = 0
                    while tries < 20:
                        #Generate a new password
                        password = str(random.randint(0,9))
                        guess = input(f'{bankt}: Guess the password (a single digit from 0-9): ').strip()
                        tries += 1
                        if guess == password:
                            typewriter_effect(f'{bankt}: You guessed it right! Here\'s your money. You got $50. Have a nice day!')
                            money += 50
                            win += 1
                            input(f'{name}: Great! I got $50 now!')
                            break
                        else:
                            typewriter_effect(f'{bankt}: Wrong password. Try again.')
                    if tries >= 20:
                        typewriter_effect(f'{bankt}: You ran out of tries. Better luck next time!')
                        input("Exit Bank.")
                elif try_now == 'no':
                    typewriter_effect(f'{bankt}: Alright, have a nice day!')
                    input(f'{name}: Oh okay...')
        elif try_again == 'no':
            typewriter_effect(f'{bankt}: Alright, have a nice day!')
            input(f'{name}: Oh okay...')
            typewriter_effect(f'{bankt}: Oh WAITT!!! I almost forgot!!.')
            input(f'{name}: Huh? WHat is it?')
            typewriter_effect(f'{bankt}: We actually have an event right now where you guess the password of a dummy account, and if you guess it right, you get $50! Do you want to try? (yes/no)')
            try_event = input(f'{name}: ')
            while try_event != 'yes' and try_event != 'no' and try_event != 'Yes' and try_event != 'No' and try_event != 'YES' and try_event != 'NO' and try_event != 'yEs' and try_event != 'nO' and try_event != 'YeS' and try_event != 'No' and try_event != 'yES' and try_event != 'nO' and try_event != 'YEs' and try_event != 'nO':
                try_event = input(f'{bankt}: Please enter yes or no: ')
            if try_event == 'yes':
                typewriter_effect(f'{bankt}: Great! The password has 1 digit. However, it\'s randomized, so after each attempt a new password is created different password. You have twenty tries to guess it right. Wanna try now? (yes/no)')
                try_now = input(f'{name}: ')
                while try_now != 'yes' and try_now != 'no' and try_now != 'Yes' and try_now != 'No' and try_now != 'YES' and try_now != 'NO' and try_now != 'yEs' and try_now != 'nO' and try_now != 'YeS' and try_now != 'No' and try_now != 'yES' and try_now != 'nO' and try_now != 'YEs' and try_now != 'nO':
                    try_now = input('Please enter yes or no: ')
                if try_now == 'yes':
                    import random
                    tries = 0
                    guess = ""
                    while tries < 20:
                        #Generate a new password
                        password = str(random.randint(0,9))
                        guess = input(f'{bankt}: Guess the password (a single digit from 0-9): ').strip()
                        tries += 1
                        if guess == password:
                            typewriter_effect(f'{bankt}: You guessed it right! Here\'s your money. You got $50. Have a nice day!')
                            money += 50
                            win += 1
                            input(f'{name}: Great! I got $50 now!')
                            break
                        else:
                            typewriter_effect(f'{bankt}: Wrong password. Try again.')
                    if tries >= 20:
                        typewriter_effect(f'{bankt}: You ran out of tries. Better luck next time!')
                        input("Exit Bank.")
                elif try_now == 'no':
                    typewriter_effect(f'{bankt}: Alright, have a nice day!')
                    input(f'{name}: Oh okay...')
            elif try_event == 'no':
                typewriter_effect(f'{bankt}: Alright, have a nice day!')
                input(f'{name}: Oh okay...')     
    elif acc == 'no':
        typewriter_effect(f'{bankt}: Oh, then unfortunately you can\'t loan from us. We\'re sorry...')
        input()
        typewriter_effect(f'{name}: Oh, okay then.')
        input()
        typewriter_effect(f'{bankt}: Alright, have a nice day!')
        input()
        typewriter_effect(f'{bankt}: Oh WAITT!!! I almost forgot!!.')
        input()
        typewriter_effect(f'{name}: Huh? WHat is it?')
        input()
        typewriter_effect('We actually have an event right now where you guess the password of a dummy account, and if you guess it right, you get $50! Do you want to try? (yes/no)')
        input()
        try_event = input(f'{name}: ')
        while try_event != 'yes' and try_event != 'no' and try_event != 'Yes' and try_event != 'No' and try_event != 'YES' and try_event != 'NO' and try_event != 'yEs' and try_event != 'nO' and try_event != 'YeS' and try_event != 'No' and try_event != 'yES' and try_event != 'nO' and try_event != 'YEs' and try_event != 'nO':
            try_event = input('Please enter yes or no: ')
        if try_event == 'yes':
            typewriter_effect(f'{bankt}: Great! The password has 1 digit. However, it\'s randomized, so after each attempt a new password is created different password. You have twenty tries to guess it right. Wanna try now? (yes/no)')
            try_now = input(f'{name}: ')
            while try_now != 'yes' and try_now != 'no' and try_now != 'Yes' and try_now != 'No' and try_now != 'YES' and try_now != 'NO' and try_now != 'yEs' and try_now != 'nO' and try_now != 'YeS' and try_now != 'No' and try_now != 'yES' and try_now != 'nO' and try_now != 'YEs' and try_now != 'nO':
                try_now = input('Please enter yes or no: ')
            if try_now == 'yes':
                import random
                tries = 0
                guess = ""
                while tries < 20:
                    #Generate a new password
                    password = str(random.randint(0,9))
                    guess = input('Guess the password (a single digit from 0-9): ').strip()
                    tries += 1
                    if guess == password:
                        typewriter_effect('You guessed it right! Here\'s your money. You got $50. Have a nice day!')
                        money += 50
                        win += 1
                        input(f'{name}: Great! I got $50 now!')
                        break
                    else:
                        typewriter_effect('Wrong password. Try again.')
                if tries >= 20:
                    typewriter_effect('You ran out of tries. Better luck next time!')
                    input("Exit Bank.")
            elif try_now == 'no':
                    typewriter_effect(f'{bankt}: Alright, have a nice day!')  #was missing f-prefix
                    input(f'{name}: Oh okay...')
        elif try_event == 'no':
                    typewriter_effect(f'{bankt}: Alright, have a nice day!')  #was missing f-prefix
                    input(f'{name}: Oh okay...')

#if player won the bank guessing game, guide offers them the psychic as a bonus money chance
if win == 1:
    typewriter_effect(f'{bname}: Oh look, it\'s the Psychic! Do you want to try and ask her how we can get money? (yes/no)')
    placeb = input(f"{name}: ")
    while placeb.lower().strip('!') not in ['yes', 'no']:
        typewriter_effect(f"{bname}: Want to go to the Psychic? Yes or no: ")
        placeb = input(f"{name}: ")
    if placeb.lower().strip('!') == 'yes':
        typewriter_effect("Walking towards the Psychic...", delay=0.135)
        input(f'{name}: Hello, can you help me get some money?')
        #moved all the psychic content inside here so it doesn't run when player says no to visiting
        typewriter_effect('Psychic: Hmmm... I have some money here that I can give you... but mwehehehe you have to guess something first... If you guess it right, you get the money. If you guess it wrong... well... let\'s just say you don\'t want to know what happens if you guess it wrong... muwahaha...')
        input(f'{name}: O-Okay... I\'ll try my best to guess it right...')
        typewriter_effect('Psychic: Alright, here\'s the question, mweheheheh. I\'m thinking of a food... something that I like... a really like... It\'s sweet and yummy... What is it? Mweheheheheheheeh... You have three tries to guess it right... muwahaha... Do you want a hint? (yes/no)')
        hint = input(f'{name}: ')
        while hint != 'yes' and hint != 'no' and hint != 'Yes' and hint != 'No' and hint != 'YES' and hint != 'NO' and hint != 'yEs' and hint != 'nO' and hint != 'YeS' and hint != 'No' and hint != 'yES' and hint != 'nO' and hint != 'YEs' and hint != 'nO':
            hint = input('I can\'t understand you dear. Say yes or no mwheheh: ')
        if hint == 'yes':
            #show choices then run the guess loop only once, not twice
            typewriter_effect('Psychic: @lright, here\'s your hint... Oh forget it... I\'ll give you four choices... Mweheheheheheh... Here they are: \n1. Ice Cream \n2. Yogurt \n3. Chicken \n4. Ogree tongue \nChoose wisely... muwahaha...')
            correct_answers = ('Ice cream','ice cream','Ice Cream')
            tries = 0
            while tries < 3:
                attempt = input(f"{name}: ")
                tries += 1
                if attempt in correct_answers:
                    typewriter_effect('You guessed it right! Here\'s your money. You got $50. Now shoo and leave me alone... muwahaha...')
                    money += 50
                    typewriter_effect('You got $50! Now let\'s head to the shop to get you equipped for your adventure!')
                    input(f'{name}: Great!')
                    break
                else:
                    typewriter_effect("Psychic: Mwehehehe wrong answerrr. Try again dearr")
            if tries == 3:
                typewriter_effect("You ran out of tries. You're cursed! Mwahaha...")
                health -= 50
                typewriter_effect('You lost 50 health points due to the psychic\'s curse. Better luck next time!')
                input(f'{name}: Oh no... My health is now {health}...')
                typewriter_effect('Psychic: Now shoo and leave me alone... muwahaha...')
                input(f'{name}: O-Okay... I\'ll go now...')
        if hint == 'no':
            typewriter_effect('Psychic: Alright, no hints for you then... mweheheheh... Here\'s the question again: I\'m thinking of a food... something that I like... a really like... It\'s sweet and yummy... What is it? Mweheheheheheheeh... You have three tries to guess it right... muwahaha...')
            correct_answers = ('Ice cream', 'ice cream', 'Ice Cream')
            tries = 0
            while tries < 3:
                attempt = input(f"{name}: ")
                tries += 1
                if attempt in correct_answers:
                    typewriter_effect('You guessed it right! Here\'s your money. You got $50. Now shoo and leave me alone... muwahaha...')
                    money += 50
                    typewriter_effect('You got $50! Now let\'s head to the shop to get you equipped for your adventure!')
                    input(f'{name}: Great!')
                    break
                else:
                    typewriter_effect("Psychic: Mwehehehe wrong answerrr. Try again dearr")
            if tries >= 3:
                typewriter_effect("You ran out of tries. You're cursed! Mwahaha...")
                health -= 50
                typewriter_effect('You lost 50 health points due to the psychic\'s curse. Better luck next time!')
                input(f'{name}: Oh no... My health is now {health}...')
                typewriter_effect('Psychic: Now shoo and leave me alone... muwahaha...')
                input(f'{name}: O-Okay... I\'ll go now...')


#player picked psychic from the start instead of going to bank
elif place == 'psychic' or place == 'Psychic' or place == 'PSYCHIC' or place == 'pSychic' or place == 'PsYchic' or place == 'PSYchic' or place == 'PSYChic':
    typewriter_effect('You went to the psychic')
    input(f'{name}: Hello, can you help me get some money?')
    typewriter_effect('Psychic: Hmmm... I have some money here that I can give you... but mwehehehe you have to guess something first... If you guess it right, you get the money. If you guess it wrong... well... let\'s just say you don\'t want to know what happens if you guess it wrong... muwahaha...')
    input(f'{name}: O-Okay... I\'ll try my best to guess it right...')
    typewriter_effect('Psychic: Alright, here\'s the question, mweheheheh. I\'m thinking of a food... something that I like... a really like... It\'s sweet and yummy... What is it? Mweheheheheheheeh... You have three tries to guess it right... muwahaha... Do you want a hint? (yes/no)')
    hint = input(f'{name}: ')
    while hint != 'yes' and hint != 'no' and hint != 'Yes' and hint != 'No' and hint != 'YES' and hint != 'NO' and hint != 'yEs' and hint != 'nO' and hint != 'YeS' and hint != 'No' and hint != 'yES' and hint != 'nO' and hint != 'YEs' and hint != 'nO':
        hint = input('I can\'t understand you dear. Say yes or no mwheheh: ')
    if hint == 'yes':
        #guess loop only runs here when yes, so it doesn't run a silent first time before the no-hint message
        typewriter_effect('Psychic: Alright, here\'s your hint... Oh forget it... I\'ll give you four choices... Mweheheheheheh... Here they are: \n1. Ice Cream \n2. Yogurt \n3. Chicken \n4. Ogree tongue \nChoose wisely... muwahaha...')
        correct_answers = ('Ice cream','ice cream','Ice Cream')
        tries = 0
        while tries < 3:
            attempt = input(f"{name}: ")
            tries += 1
            if attempt in correct_answers:
                typewriter_effect('You guessed it right! Here\'s your money. You got $50. Now shoo and leave me alone... muwahaha...')
                money += 50
                typewriter_effect('You got $50! Now let\'s head to the shop to get you equipped for your adventure!')
                input(f'{name}: Great!')
                break
            else:
                typewriter_effect("Psychic: Mwehehehe wrong answerrr. Try again dearr")
        if tries >= 3:
            typewriter_effect("You ran out of tries. You're cursed! Mwahaha...")
            health -= 50
            typewriter_effect('You lost 50 health points due to the psychic\'s curse. Better luck next time!')
            input(f'{name}: Oh no... My health is now {health}...')
            typewriter_effect('Psychic: Now shoo and leave me alone... muwahaha...')
            input(f'{name}: O-Okay... I\'ll go now...')
    if hint == 'no':
        typewriter_effect('Psychic: Alright, no hints for you then... mweheheheh... Here\'s the question again: I\'m thinking of a food... something that I like... a really like... It\'s sweet and yummy... What is it? Mweheheheheheheeh... You have three tries to guess it right... muwahaha...')
        correct_answers = ('Ice cream', 'ice cream', 'Ice Cream')
        tries = 0
        while tries < 3:
            attempt = input(f"{name}: ")
            tries += 1
            if attempt in correct_answers:
                typewriter_effect('You guessed it right! Here\'s your money. You got $50. Now shoo and leave me alone... muwahaha...')
                money += 50
                typewriter_effect('You got $50! Now let\'s head to the shop to get you equipped for your adventure!')
                input(f'{name}: Great!')
                break
            else:
                typewriter_effect("Psychic: Mwehehehe wrong answerrr. Try again dearr")
        if tries >= 3:
            typewriter_effect("You ran out of tries. You're cursed! Mwahaha...")
            health -= 50
            typewriter_effect('You lost 50 health points due to the psychic\'s curse. Better luck next time!')
            input(f'{name}: Oh no... My health is now {health}...')
            typewriter_effect('Psychic: Now shoo and leave me alone... muwahaha...')
            input(f'{name}: O-Okay... I\'ll go now...')
#Continue the adventure...
input()
typewriter_effect('You head to the shop to get equipped for your adventure.')
input()
typewriter_effect('Which shop do you wanna go to? \n1. Blacksmith - purchase/upgrade/sell weapons and armors. \n2. Wizard Tower - purchase/upgrade/sell tomes, staff, and spells. \n3. Merchant - purchase/sell accessories, miscellaneous, and other items. \n0. Open Inventory')
store = input(f'{name}: ')
while store != '1' and store != '2' and  store != '3' and store != '0' and store != '1.' and store != '2.' and store != '3.' and store != '0.' and store != 'Blacksmith' and store != 'blacksmith' and store != 'Wizard Tower' and store != 'Wizard tower' and store != 'wizard tower' and store != 'Merchant' and store != 'merchant':
    typewriter_effect(f'{bname}: Uhh where is that? Can you pls try again?')
    store = input(f'Enter correct option: ')
if store in ['1', '1.', 'Blacksmith', 'blacksmith'] and classs in ['Warrior', 'Tank', 'Archer']:
    typewriter_effect(f'Welcome to my shop, {name}!')
    typewriter_effect(input(f'{name}: Hello!'))
    input()
    typewriter_effect('Blacksmith Dude: Heyo! What do you wanna do at my shop? You got something you wanna buy, or something you wanna sell?(buy/sell)')
    bs = str(input())
    while bs != 'buy' and bs != 'sell' and bs != 'Buy' and bs != 'Sell':
        typewriter_effect('Blacksmith Dude: Oopsie doopsie, my guy! You chose a wrong option. What do you wanna do? Buy or sell?')
        bs = input(f"{name}: ")
    if bs == 'buy' or bs == 'Buy':
        typewriter_effect('Cool! What are you lookin\' for? Are you look for armor or weapon? (armor/weapon)')
        arwe = input()
        while arwe != 'armor' and arwe != 'Armor' and arwe != 'weapon' and arwe != 'Weapon':
            typewriter_effect('Dude please choose a valid option: ')
            arwe = input(f"{name}: ")
        if arwe == 'weapon' or arwe == 'Weapon':
            typewriter_effect('Cool! Please tell me the number of the item that you wanna buy: \n1. Sword -- $20; 5-8 damage. \n2. Axe -- $15; 3-6 damage. \n3. Dagger -- $10; 1-4 damage.')
            weapon = input()
            while weapon != '1' and weapon != '2' and weapon != '3':
                typewriter_effect("Bro I don't sell that weapon. Choose from the options I mentioned: ")
                weapon = input(f"{name}: ")
            if weapon == '1':
                typewriter_effect("Excellent choice! That'll be $20.")
                input(f"{name}: (pay)")
                if money < 20:  #check BEFORE taking the money so we don't charge then reject
                    typewriter_effect("Oh dude. It seems that you don't have enough money! Come back next time : )")
                elif money >= 20:
                    money -= 20
                    typewriter_effect("Fantastic!!")
                    typewriter_effect(f"{name}: Nice!")
                    input()
                    typewriter_effect("Got something else you wanna buy? (yes/no)")
                    buy_bsagain = input(f"{name}: ")
                    while buy_bsagain.lower() not in ['yes', 'no']:
                        typewriter_effect("Dude, it's a simple yes or no. Tell me : )")
                        buy_bsagain = input(f"{name}: ")
                    if buy_bsagain.lower() == 'yes':
                        typewriter_effect("Oopss I forgot, dude. Our creator didn't want to write a long code on this part so he skipped it. Come back again next time (when he finishes coding this part) and I wish you luck on your adventure!")
                        input(f"{name}: Oh, okay. Thanks!")
                    elif buy_bsagain == 'No' or buy_bsagain == 'no':
                        typewriter_effect("Alrighty! See you next time, dude. I wish you luck on your adventure! : )")
            elif weapon == '2':
                typewriter_effect("Excellent choice! That'll be $15.")
                input(f"{name}: (pay)")
                if money < 15:  #check before deducting
                    typewriter_effect("Oh dude. It seems that you don't have enough money! Come back next time : )")
                elif money >= 15:
                    money -= 15
                    typewriter_effect("Fantastic!!")
                    input(f"{name}: Nice!")
                    input()
                    typewriter_effect("Got something else you wanna buy? (yes/no)")
                    buy_bsagain = input(f"{name}: ")
                    while buy_bsagain.lower() not in ['yes', 'no']:
                        typewriter_effect("Dude, it's a simple yes or no. Tell me : )")
                        buy_bsagain = input(f"{name}: ")
                    if buy_bsagain.lower() == 'yes':
                        typewriter_effect("Oopss I forgot, dude. Our creator didn't want to write a long code on this part so he skipped it. Come back again next time (when he finishes coding this part) and I wish you luck on your adventure!")
                        input(f"{name}: Oh, okay. Thanks!")
                    elif buy_bsagain == 'No' or buy_bsagain == 'no':
                        typewriter_effect("Alrighty! See you next time, dude. I wish you luck on your adventure! : )")
            elif weapon == '3':
                typewriter_effect("Excellent choice! That'll be $10.")
                input(f"{name}: (pay)")
                if money < 10:  #check before deducting
                    typewriter_effect("Oh dude. It seems that you don't have enough money! Come back next time : )")
                elif money >= 10:
                    money -= 10
                    typewriter_effect("Fantastic!!")
                    input(f"{name}: Nice!")
                    input()
                    typewriter_effect("Got something else you wanna buy? (yes/no)")
                    buy_bsagain = input(f"{name}: ")
                    while buy_bsagain.lower() not in ['yes', 'no']:
                        typewriter_effect("Dude, it's a simple yes or no. Tell me : )")
                        buy_bsagain = input(f"{name}: ")
                    if buy_bsagain.lower() == 'yes':
                        typewriter_effect("Oopss I forgot, dude. Our creator didn't want to write a long code on this part so he skipped it. Come back again next time (when he finishes coding this part) and I wish you luck on your adventure!")
                        input(f"{name}: Oh, okay. Thanks!")
                    elif buy_bsagain.lower() == 'no':
                        typewriter_effect("Alrighty! See you next time, dude. I wish you luck on your adventure! : )")
                        input()
                
    elif bs == 'sell' or bs == 'Sell':
        typewriter_effect(f"Oopps, dude. It seems that you don't have any items to sell.")
        input(f"{name}: Oh, okay...")
        typewriter_effect("Man, you should've chosen the buy option. Our creator didn't bother to duplicate the code for this part, so you would have to restart the game.")
        input(f"{name}: Alright")
        typewriter_effect("End game? Press enter.")
        input()
        sys.exit()


#Enemies - base HP and randomized damage ranges for each enemy type
ogre_hp = 60
ogre_dmg = random.randint(6,9)

goblin_hp = 35
goblin_dmg = random.randint(2,5)

bat_hp = 20
bat_dmg = random.randint(1,4)

giant_hp = 100
giant_dmg = random.randint(12,18)

unknown_abomination_hp = 150
unknown_abomination_dmg = random.randint(25,40)

#Attacks - damage = base stat + weapon random range, calculated on game start
swordatt = strength + random.randint(5,8)
axeatt = strength + random.randint(3,6)
daggeratt = strength + random.randint(1,4)

staffatt = intelligence + random.randint(5,8)
wandatt = intelligence + random.randint(3,6)
orbatt = intelligence + random.randint(1,4)

crossbow = strength + random.randint(5,8)
bow = strength + random.randint(3,6)
javelin = strength + random.randint(1,4)

spiked_shield = strength + random.randint(5,8)
war_hammer = strength + random.randint(3,6)
spiked_gloves = strength + random.randint(1,4)

#Spells
#fire, ice, lightning effects, add them
fireball_attack = random.randint(3,7) + staffatt + wandatt + orbatt
iceball_attack = random.randint(2,5) + staffatt + wandatt + orbatt
lightning_attack =  random.randint(3, 5) + staffatt + wandatt + orbatt

#Armor
shield = defense + random.randint(4,7)
chestplate = defense + random.randint(2,5)
helmet = defense + random.randint(2,4)

#Potions
small_health_potion = health + random.randint(10,18)
large_health_potion = health + random.randint(20,40)

small_mana_potion = mana + random.randint(5,15)
large_mana_potion = mana + random.randint(15,30)

damage_potion_strength = strength + random.randint(10,20)
damage_potion_intelligence = intelligence + random.randint(10,20)

small_defense_potion = defense + random.randint(10,15)
large_defense_potion = defense + random.randint(15,20)

#Traps
spike_trap_dmg = random.randint(3,8)
explosion_trap_dmg = random.randint(10,15)
dark_curse_trap_dmg = random.randint(5,20)
smoke_trap_dmg = random.randint(1,3)
confusion_trap_dmg = random.randint(2,4)

spike_trap_name = "Spike Trap"
explosion_trap_name = "Explosion Trap"
dark_curse_trap_name = "Dark Curse Trap"
smoke_trap_name = "Smoke Trap"
confusion_trap_name = "Confusion Trap"

typewriter_effect(f"{bname}: I think you're ready now! Do you wanna go and explore the dungeon? (yes/no)")
dungeon_explore = input(f"{name}: ")
while dungeon_explore.lower() not in ['yes', 'no']:
    typewriter_effect("I don't think it's safe to go that way... Try again: ")
    dungeon_explore = str(input(f"{name}: "))
if dungeon_explore.lower() == 'yes':
    typewriter_effect(f"{bname}: Great! Let's go")
    input()
    typewriter_effect('Entering dungeon...')
typewriter_effect(f"{bname}: We're inside! There are two pathways, left and right. Which way do you want to go? (left/right)")
direction1 = input(f"{name}: ")
while direction1 != 'left' and direction1 != 'Left' and direction1 != 'Right' and direction1 != 'right':
    typewriter_effect(f"{bname}: Wrong direction. Try again! ")
    direction1 = input(f"{name}: ")
if direction1 == 'left' or direction1 == 'Left' or direction1 == 'Right' or direction1 == 'right':
    typewriter_effect("Walking...", delay=0.25)
    trap = random.randint(0,10)
    if trap == 0:
        health -= spike_trap_dmg
        typewriter_effect(f"Ouch! You lost {spike_trap_dmg} Health points!")
    elif trap == 1:
        health -= explosion_trap_dmg
        typewriter_effect(f"Boom! You lost {explosion_trap_dmg} Health points!")
    elif trap == 2:
        health -= dark_curse_trap_dmg
        typewriter_effect(f"A dark curse! You lost {dark_curse_trap_dmg} Health points!")
    elif trap == 3:
        strength -= smoke_trap_dmg
        typewriter_effect(f"Smoke fills the air! Your strength is reduced by {smoke_trap_dmg}!")
    elif trap == 4:
        strength -= confusion_trap_dmg
        typewriter_effect(f"You feel confused! Your strength is reduced by {confusion_trap_dmg}!")
    elif trap in (5, 6, 7, 8, 9, 10):
        typewriter_effect(f"{bname}: Phew! {name}, luckily you didn't encounter any traps.")
        typewriter_effect(f"{bname}: Continue walking?")
input()
typewriter_effect("Walking...", delay=0.25)
encounter1 = random.randint(0,2)
if encounter1 == 0:
    enemy = 'An Ogre'
    enemy1 = 'Ogre'
    enemyhp = '60'
    enemy_dmg = '6-9'
elif encounter1 == 1:
    enemy = 'A Goblin'
    enemy1 = 'Goblin'
    enemyhp = '35'
    enemy_dmg = '2-5'
elif encounter1 == 2:
    enemy = 'A Bat'
    enemy1 = 'Bat'
    enemyhp = '20'
    enemy_dmg = '1-4'

typewriter_effect(f"{bname}: Look! {enemy}!!")
input()
typewriter_effect(f"{bname}: They have {enemyhp} health points and could deal {enemy_dmg} damge. Do you want to attack it or do you want to try and escape?(attack/escape)")
escape_luck = random.randint(0,5)
decision1 = input(f"{name}: ")
while decision1 != 'attack' and decision1 != 'escape':
    typewriter_effect(f"{bname}: Quick, you have to decide!")
    decision1 = input(f"{name}: ")
if decision1 == 'escape' and escape_luck <= 4:
    typewriter_effect(f"{bname}: Oh no! Your escape failed. You have to face and defeat the {enemy1}. You can do it!!")
elif decision1 == 'attack':
    typewriter_effect(f"{bname}: Ohh brave! I like it! Go {name}, defeat that {enemy1}!")
input()
typewriter_effect(f"{enemy1}: RAHHH!!")

typewriter_effect(f"{name}: Slips... aaaaaAAAAHHHHH!!!")
input()
typewriter_effect(f"{bname}: OH NOOO!!!! ")
input()
typewriter_effect(f"{name}: HELP ME!")
input()
typewriter_effect(f"{bname}: Aghh!!! I forgot to telll you...")
input()
typewriter_effect(f"{bname}: There are several almost unnoticeable holes in the dungeon... They're deep and it's impossible to climb up without losing your life... I can't climb down either... because unfortunately, the person who created me doesn't want to for the sake of the plot...")
input()
typewriter_effect(f"{bname}: Anyways, just keep moving forward without me! We'll eventually see each other... hopefully")
input()
typewriter_effect(f"{bname}: Good luck! Just follow everything I told you so far!!")
input(f"{name}: Okay...")

#Traps - randomize damage values upfront so they feel different each run
spike_trap = random.randint(3,8)
explosion_trap = random.randint(10,15)
dark_curse_trap = random.randint(5,20)
smoke_trap = random.randint(1,3)
confusion_trap = random.randint(2,4)

spike_trap_name = "Spike Trap"
explosion_trap_name = "Explosion Trap"
dark_curse_trap_name = "Dark Curse Trap"
smoke_trap_name = "Smoke Curse Trap"
confusion_trap_name = "Confusion Trap"

#Buff names
healing_potion_name = "Healing Potion"
strength_potion_name = "Strength Potion"

#Enemy names
beast_name = "Beast"
bat_name = "Bat"
goblin_name = "Goblin"
giant = "Giant"


trap_name = ""
buff_name = ""
enemy = ""
trap_dmg = 0
dobuff = 0
enedam = 0
goldearn = 0
lock = ""
input("Move forward? ")
typewriter_effect("Walking...", delay=0.2)

#main dungeon walk loop - runs 20 steps, each step has a random chance to trigger a trap, monster, potion, or gold
for step in range(20):
    walk = random.randint(0,30)
    typewriter_effect('Walking...', delay=0.16)

    if walk in {0, 9, 15, 17}:  #numbers that will trigger the trap
        typewriter_effect('A trap triggered!')

        #Reroll which trap will appear
        dtrap = random.randint(1,6)
        if dtrap == 1:
            trap_name = 'Spike Trap'
            trap_dmg = random.randint(3, 8)
            input(f"You got hit by a {trap_name} for {trap_dmg} damage on your health.")
            health -= trap_dmg
            typewriter_effect(f"You now have {health} health points.")
            if health <= 0:
                typewriter_effect("You died...", delay=0.321)
                sys.exit()
        elif dtrap == 2:
            trap_name = 'Explosion Trap'
            trap_dmg = random.randint(10, 15)
            input(f"You got hit by a {trap_name} for {trap_dmg} damage on your health.")
            health -= trap_dmg
            typewriter_effect(f"You now have {health} health points.")
            if health <= 0:
                typewriter_effect("You died...", delay=0.321)
                sys.exit()
        elif dtrap == 3:
            trap_name = 'Dark Curse Trap'
            trap_dmg = random.randint(5, 20)
            input(f"You got hit by a {trap_name} for {trap_dmg} damage on your health.")
            health -= trap_dmg
            typewriter_effect(f"You now have {health} health points.")
            if health <= 0:
                typewriter_effect("You died...", delay=0.321)
                sys.exit()
        elif dtrap in (4, 5):  # smoke twice as likely, like before
            trap_name = 'Smoke Trap'
            trap_dmg = random.randint(1, 3)
            input(f"You got hit by a {trap_name}. Your strength is reduced by {trap_dmg}.")
            strength -= trap_dmg
            typewriter_effect(f"You now have {strength} strength points.")
        else:  # dtrap == 6
            trap_name = 'Confusion Trap'
            trap_dmg = random.randint(2, 4)
            input(f"You got hit by a {trap_name}. Your strength is reduced by {trap_dmg}.")
            strength -= trap_dmg
            typewriter_effect(f"You now have {strength} strength points.")

        input('Continue.')
    elif walk in {3, 7, 14, 21}: #MONSTER
        typewriter_effect("A monster has appeared!")

        enemy_number = random.randint(0, 3)
        if enemy_number == 1:
            enemy = 'Beast'
            enemyhp = 60
            enedam = random.randint(6, 10)
            typewriter_effect(f"It's a {enemy}!")
            while enemyhp > 0:
                print('Placeholder')
                input()
                typewriter_effect("What do you do?")
                input(f"""
                    1. 
                    """)
                break  #fight system not built yet - break to stop the infinite loop
                
            if enemyhp <= 0:
                print("placeholder")

            if health <= 0:
                typewriter_effect("You died.....", delay=0.321)
                sys.exit()
    
    elif walk in {6, 5, 8, 20}:  #changed 0 to 6 because 0 was already in the trap set so potions never triggered
        typewriter_effect("You found a buff potion!")
        dbuff = random.randint(0, 1)

        if dbuff == 0:
            buff_name = 'Healing Potion'
            dobuff = random.randint(4, 10)
            input("Drink Potion.")
            typewriter_effect("Drinking...", delay=0.16)
            input(f"You drank a {buff_name} and gained {dobuff} health points.")
            health += dobuff
            typewriter_effect(f"You now have {health} health points.")

        elif dbuff == 1:
            buff_name = 'Strength Potion'
            dobuff = random.randint(3, 8)
            input("Drink Potion.")
            typewriter_effect("Drinking...", delay=0.16)
            input(f"You drank a {buff_name} and gained {dobuff} strength points.")
            strength += dobuff
            typewriter_effect(f"You now have {strength} strength points.")
        
        input("Continue.")
    elif walk in {1, 22, 13}:
        typewriter_effect("You found gold!")
        goldearn = random.randint(5,10)
        input("Take gold.")
        money += goldearn
        typewriter_effect(f"You now have {money} gold coins.")


    elif walk in {25}:
        typewriter_effect("You found a GOLDEN CHEST!!!")
        goldearn = random.randint(25, 50)
        tries = 0
        typewriter_effect("However, it's locked by a fixed three-digit password. You have three tries; if you fail, something bad might happen.")
        lock = input("Guess: ")
        while lock != "123" and tries < 3:
            tries += 1
            typewriter_effect("It's not working... Try again.")
            lock = input(f"{name}: ")
        if lock == "123" and tries <= 3:
            typewriter_effect("It opened!")
            money += goldearn
            typewriter_effect(f"You found {goldearn} gold coins inside!")
            input()
            typewriter_effect(f"You now have {money} gold coins.")
        else:
            typewriter_effect("Boom!💥💥💥", delay=0.02)
            typewriter_effect("Oh no, it exploded!")
            health -= random.randint(15, 30)
            input()
            typewriter_effect(f"You got hit. Your health is now {health}.")
            if health <= 0:
                typewriter_effect("You died...", delay=0.321)
                sys.exit()
